# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import modules.shared.persons_pb2 as persons__pb2

class PersonsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllPersons = channel.unary_unary(
                '/PersonsService/GetAllPersons',
                request_serializer=persons__pb2.Empty.SerializeToString,
                response_deserializer=persons__pb2.PersonsMessage.FromString,
                )
        self.GetPerson = channel.unary_unary(
                '/PersonsService/GetPerson',
                request_serializer=persons__pb2.PersonIdMessage.SerializeToString,
                response_deserializer=persons__pb2.PersonMessage.FromString,
                )


class PersonsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllPersons(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllPersons': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPersons,
                    request_deserializer=persons__pb2.Empty.FromString,
                    response_serializer=persons__pb2.PersonsMessage.SerializeToString,
            ),
            'GetPerson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPerson,
                    request_deserializer=persons__pb2.PersonIdMessage.FromString,
                    response_serializer=persons__pb2.PersonMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PersonsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PersonsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllPersons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PersonsService/GetAllPersons',
            persons__pb2.Empty.SerializeToString,
            persons__pb2.PersonsMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PersonsService/GetPerson',
            persons__pb2.PersonIdMessage.SerializeToString,
            persons__pb2.PersonMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
