# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persons.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpersons.proto\"X\n\rPersonMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"1\n\x0ePersonsMessage\x12\x1f\n\x07persons\x18\x01 \x03(\x0b\x32\x0e.PersonMessage\"\x1d\n\x0fPersonIdMessage\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2i\n\x0ePersonsService\x12(\n\rGetAllPersons\x12\x06.Empty\x1a\x0f.PersonsMessage\x12-\n\tGetPerson\x12\x10.PersonIdMessage\x1a\x0e.PersonMessageb\x06proto3')



_PERSONMESSAGE = DESCRIPTOR.message_types_by_name['PersonMessage']
_PERSONSMESSAGE = DESCRIPTOR.message_types_by_name['PersonsMessage']
_PERSONIDMESSAGE = DESCRIPTOR.message_types_by_name['PersonIdMessage']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
PersonMessage = _reflection.GeneratedProtocolMessageType('PersonMessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONMESSAGE,
  '__module__' : 'persons_pb2'
  # @@protoc_insertion_point(class_scope:PersonMessage)
  })
_sym_db.RegisterMessage(PersonMessage)

PersonsMessage = _reflection.GeneratedProtocolMessageType('PersonsMessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONSMESSAGE,
  '__module__' : 'persons_pb2'
  # @@protoc_insertion_point(class_scope:PersonsMessage)
  })
_sym_db.RegisterMessage(PersonsMessage)

PersonIdMessage = _reflection.GeneratedProtocolMessageType('PersonIdMessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONIDMESSAGE,
  '__module__' : 'persons_pb2'
  # @@protoc_insertion_point(class_scope:PersonIdMessage)
  })
_sym_db.RegisterMessage(PersonIdMessage)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'persons_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_PERSONSSERVICE = DESCRIPTOR.services_by_name['PersonsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSONMESSAGE._serialized_start=17
  _PERSONMESSAGE._serialized_end=105
  _PERSONSMESSAGE._serialized_start=107
  _PERSONSMESSAGE._serialized_end=156
  _PERSONIDMESSAGE._serialized_start=158
  _PERSONIDMESSAGE._serialized_end=187
  _EMPTY._serialized_start=189
  _EMPTY._serialized_end=196
  _PERSONSSERVICE._serialized_start=198
  _PERSONSSERVICE._serialized_end=303
# @@protoc_insertion_point(module_scope)
