apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-persons-api
  name: grpc-persons-api
spec:
  ports:
  - name: "5006"
    port: 5006
    targetPort: 5006
    nodePort: 30002
  selector:
    service: grpc-persons-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-persons-api
  name: grpc-persons-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc-persons-api
  template:
    metadata:
      labels:
        service: grpc-persons-api
    spec:
      containers:
      - image: ksaleh/grpc-persons-api:latest
        name: grpc-persons-api
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
