apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-persons-api
  name: kafka-persons-api
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 30003
  selector:
    service: kafka-persons-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-persons-api
  name: kafka-persons-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-persons-api
  template:
    metadata:
      labels:
        service: kafka-persons-api
    spec:
      containers:
      - image: ksaleh/kafka-persons-api:latest
        name: kafka-persons-api
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
